services:
  database:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME:?error}
      POSTGRES_USER: ${DB_USER:?error}
      POSTGRES_PASSWORD: ${DB_PASS?error}
    networks:
      wagewhiz:
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgweb:
    restart: unless-stopped
    image: sosedoff/pgweb
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgres://${DB_USER:?error}:${DB_PASS?error}@database:5432/${DB_NAME:?error}?sslmode=disable
    depends_on:
      - database
    networks:
      wagewhiz:

  meilisearch:
    build: ./apps/meilisearch
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=${MEILISEARCH_MASTER_KEY:?error}
    networks:
      wagewhiz:

  influxdb:
    image: influxdb:2.7
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_USER:?error}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_PASS:?error}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_ORG:-wagewhiz}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_BUCKET:-wagewhiz}
    networks:
      wagewhiz:
    volumes:
      - influxdb-data:/var/lib/influxdb2

networks:
  wagewhiz:
    driver: bridge

volumes:
  postgres-data:
  influxdb-data:
