//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

pub use super::people::Entity as People;
pub use super::person_types::Entity as PersonTypes;
pub use super::teams::Entity as Teams;
pub use super::user_accounts::Entity as UserAccounts;
