[package]
name = "api"
version = "0.0.1"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
argon2 = "0.5.3"
axum = "0.7.4"
axum-extra = { version = "0.9.2", features = ["cookie"] }
axum-macros = "0.4.1"
base64-url = "2.0.2"
bb8 = "0.8.3"
diesel = { version = "2.1.4", features = ["uuid", "time"] }
diesel-async = { version = "0.4.1", features = ["postgres", "bb8"] }
dotenv = "0.15.0"
envy = "0.4.2"
once_cell = "1.19.0"
pasetors = "0.6.8"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
thiserror = "1.0.56"
time = { version = "0.3.34", features = ["serde", "formatting", "parsing"] }
tokio = { version = "1.36.0", features = ["full"] }
tower-http = { version = "0.5.1", features = ["cors"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
uuid = { version = "1.7.0", features = ["serde"] }
validator = { version = "0.16.1", features = ["derive"] }
