[package]
name = "api"
version = "0.0.1"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
argon2 = "0.5.1"
axum = "0.6.19"
axum-macros = "0.3.8"
base64-url = "2.0.0"
bb8 = "0.8.1"
diesel = { version = "2.1.0", features = ["uuid", "time"] }
diesel-async = { version = "0.3.1", features = ["postgres", "bb8"] }
dotenv = "0.15.0"
envy = "0.4.2"
once_cell = "1.18.0"
pasetors = "0.6.7"
serde = { version = "1.0.171", features = ["derive"] }
serde_json = "1.0.103"
thiserror = "1.0.43"
time = { version = "0.3.23", features = ["serde", "formatting", "parsing"] }
tokio = { version = "1.29.1", features = ["full"] }
tower-http = { version = "0.4.3", features = ["cors"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
uuid = { version = "1.4.1", features = ["serde"] }
validator = { version = "0.16.1", features = ["derive"] }
